spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/fashion_shop_website?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${MY_USERNAME}
    password: ${MY_PASSWORD}
  mvc:
    hidden-method:
      filter:
        enabled: true
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
